# Generated by Django 5.1.5 on 2025-03-17 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hotel_staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(choices=[('reception', 'Reception'), ('housekeeping', 'Housekeeping'), ('management', 'Management'), ('kitchen', 'Kitchen')], default='reception', max_length=50)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_active_staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission'),
        ),
    ]
