# Generated by Django 5.1.5 on 2025-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hotelstaff_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaff',
            name='alternate_mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='hotel_gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='landline_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='owner_aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_aadhar/'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='owner_pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_pancard/'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='shop_aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_aadhar/'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='shop_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_licenses/'),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='shop_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_main/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_aadhar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pancard_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_pancard/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
